package BuisinessLogic;

import DataAccess.BillDAO;
import DataModel.Bill;
import DataModel.Client;

import javax.swing.table.DefaultTableModel;
import java.util.List;

public class BillBLL {
    private BillDAO billDAO;
    public BillBLL() {
        this.billDAO = new BillDAO();
    }

    public void insertBill(Bill bill){
        billDAO.insertBill(bill);
    }

    /**
     * create a table model for the bills generated by the orders made
     * @return the table model
     */
    public DefaultTableModel getBillTableModel(){
        String[] colums = new String[]{"ID", "ID Order", "ID Client", "ID Product", "Total Price"};
        DefaultTableModel model = new DefaultTableModel(colums, 0);
        List<Bill> bills = billDAO.findAllBills();
        for(Bill bill : bills){
            model.addRow(new Object[]{bill.id(), bill.idOrder(), bill.idClient(), bill.idProduct(), bill.total_price()});
        }
        return model;
    }

    /**
     * refresh the bill table
     * @param model
     */
    public void refreshBillTable(DefaultTableModel model){
        model.setRowCount(0);
        List<Bill> bills = billDAO.findAllBills();
        for(Bill bill : bills){
            model.addRow(new Object[]{
                    bill.id(), bill.idOrder(), bill.idClient(), bill.idProduct(), bill.total_price()
            });
        }
    }
}
